function productRecipeCost(productId){ return state.productRecipes.filter(x=>x.product_id===productId).reduce((sum,x)=>{ const r=state.recipes.find(y=>y.id===x.recipe_id); if(!r) return sum; return sum + recipeUnitCost(r)*toBaseUnit(x.quantity_used,x.unit); },0); }
function computedProductCost(p){ return num(p.product_cost || p.manual_product_cost) || (productRecipeCost(p.id)+num(p.packaging_cost)); }
function enrichedProduct(p){ const cost=computedProductCost(p); const offlineProfit=num(p.offline_price)-cost; const onlineRevenue=num(p.online_price); const comm=onlineRevenue*num(p.commission_percent||settings.defaultCommission)/100; const onlineProfit=onlineRevenue-cost-comm; return {...p,product_cost:cost,offline_profit:offlineProfit,online_profit:onlineProfit,offline_margin:margin(offlineProfit,num(p.offline_price)),online_margin:margin(onlineProfit,onlineRevenue)}; }
async function saveProductV15(){ const name=val('productName').trim(); if(!name) return alert('Product name required'); const row={name,category:val('productCategory'),brand_id:val('productBrand')||null,branch_id:val('productBranch')||null,offline_price:num(val('offlinePrice')),online_price:num(val('onlinePrice')),packaging_cost:num(val('packagingCost')),commission_percent:num(val('commissionPercent'))||settings.defaultCommission,manual_product_cost:num(val('manualProductCost'))||null,active:true,updated_at:new Date().toISOString()}; if(state.editing.product) await dbUpdate('products',state.editing.product,row); else await dbInsert('products',row); clearProductForm(); await refreshAll(false); renderProducts(); }
function clearProductForm(){ state.editing.product=null; ['productName','productCategory','offlinePrice','onlinePrice','packagingCost','manualProductCost'].forEach(id=>setVal(id,'')); setVal('commissionPercent',settings.defaultCommission); }
function editProduct(id){ const p=state.products.find(x=>x.id===id); if(!p)return; state.editing.product=id; setVal('productName',p.name); setVal('productCategory',p.category); setVal('productBrand',p.brand_id); setVal('productBranch',p.branch_id); setVal('offlinePrice',p.offline_price); setVal('onlinePrice',p.online_price); setVal('packagingCost',p.packaging_cost); setVal('commissionPercent',p.commission_percent||settings.defaultCommission); setVal('manualProductCost',p.manual_product_cost||p.product_cost||''); showTab('products'); scrollTo(0,0); }
async function deleteProduct(id){ if(confirm('Delete product?')){ await dbDelete('products',id); await refreshAll(false); renderProducts(); }}
async function addProductRecipe(){ if(!val('builderProduct')||!val('builderRecipe')) return alert('Select product and recipe'); await dbInsert('product_recipes',{product_id:val('builderProduct'),recipe_id:val('builderRecipe'),quantity_used:num(val('builderQty')),unit:val('builderUnit')}); setVal('builderQty',''); await refreshAll(false); renderProductRecipes(); renderProducts(); }
async function deleteProductRecipe(id){ await dbDelete('product_recipes',id); await refreshAll(false); renderProductRecipes(); renderProducts(); }
function openProductRecipeBuilder(){ byId('builderProduct').focus(); }
function renderProductSelectors(){ ['productBrand','productBrandFilter','expenseBrand'].forEach(id=>{ if(byId(id)) byId(id).innerHTML=(id.includes('Filter')?'<option value="">All Brands</option>':'')+optionList(state.brands).replace('<option value="">Select</option>',''); }); ['productBranch','productBranchFilter','expenseBranch'].forEach(id=>{ if(byId(id)) byId(id).innerHTML=(id.includes('Filter')?'<option value="">All Branches</option>':'')+optionList(state.branches).replace('<option value="">Select</option>',''); }); ['builderProduct','cartProduct'].forEach(id=>{ if(byId(id)) byId(id).innerHTML=optionList(state.products); }); }
function renderProductRecipes(){ const pid=val('builderProduct')||state.products[0]?.id; const list=state.productRecipes.filter(x=>x.product_id===pid); byId('productRecipeList').innerHTML=table(['Recipe','Qty','Unit','Cost','Actions'],list.map(x=>{ const r=state.recipes.find(y=>y.id===x.recipe_id)||{}; const cost=recipeUnitCost(r)*toBaseUnit(x.quantity_used,x.unit); return `<tr><td>${escapeHtml(r.name||'')}</td><td>${x.quantity_used}</td><td>${x.unit||''}</td><td>${money(cost)}</td><td><button class="btn-danger" onclick="deleteProductRecipe('${x.id}')">Delete</button></td></tr>`; })); }
function renderProducts(){ renderProductSelectors(); renderRecipeSelectors(); renderProductRecipes(); const q=val('productSearch').toLowerCase(), bf=val('productBrandFilter'), brf=val('productBranchFilter'), sort=val('productSort')||'profit_desc'; let list=state.products.map(enrichedProduct).filter(p=>(p.name||'').toLowerCase().includes(q)&&(!bf||p.brand_id===bf)&&(!brf||p.branch_id===brf)); list.sort((a,b)=>sort==='margin_desc'?b.online_margin-a.online_margin:sort==='name_asc'?(a.name||'').localeCompare(b.name||''):sort==='cost_desc'?b.product_cost-a.product_cost:b.online_profit-a.online_profit); byId('productsTable').innerHTML=table(['Product','Brand','Branch','Cost','Offline Price','Online Price','Offline Profit','Online Profit','Offline Margin','Online Margin','Updated','Actions'],list.map(p=>`<tr><td><strong>${escapeHtml(p.name)}</strong><br><span class="small">${escapeHtml(p.category||'')}</span></td><td>${brandName(p.brand_id)}</td><td>${branchName(p.branch_id)}</td><td>${money(p.product_cost)}</td><td>${money(p.offline_price)}</td><td>${money(p.online_price)}</td><td class="${p.offline_profit>=0?'profit':'loss'}">${money(p.offline_profit)}</td><td class="${p.online_profit>=0?'profit':'loss'}">${money(p.online_profit)}</td><td>${pct(p.offline_margin)}</td><td>${pct(p.online_margin)}</td><td>${(p.updated_at||p.created_at||'').slice(0,10)}</td><td><button onclick="editProduct('${p.id}')">Edit</button><button class="btn-danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`)); }
function exportProductsCSV(){ downloadCSV('khumbuka_products_profitability.csv', state.products.map(enrichedProduct)); }
