function recipeUnitCost(recipe){ const cost=recipeTotalCost(recipe.id); const y=toBaseUnit(recipe.yield_quantity,recipe.yield_unit); return y?cost/y:0; }
function recipeTotalCost(recipeId){ return state.recipeItems.filter(x=>x.recipe_id===recipeId).reduce((sum,item)=>{ const ing=state.ingredients.find(i=>i.id===item.ingredient_id); if(!ing) return sum; const eff=num(ing.effective_cost ?? effectiveCost(ing.purchase_price,ing.wastage_percent)); const baseQty=toBaseUnit(item.quantity,item.unit); const wasteFactor=1+(num(item.waste_percent)/100); return sum + eff*baseQty*wasteFactor; },0); }
async function saveRecipe(){ const name=val('recipeName').trim(); if(!name) return showWarning('Recipe name required'); const row={name,category:val('recipeCategory'),yield_quantity:num(val('recipeYieldQty')),yield_unit:val('recipeYieldUnit'),notes:val('recipeNotes'),active:val('recipeActive')==='true',updated_at:new Date().toISOString()}; let saved=null; if(state.editing.recipe) saved=await dbUpdate('recipes',state.editing.recipe,row); else saved=await dbInsert('recipes',row); if(!saved) return; showToast(state.editing.recipe?'Recipe updated successfully.':'Recipe created successfully.'); clearRecipeForm(); await refreshAll(false); renderRecipes(); renderRecipeSelectors(); }
function clearRecipeForm(){ state.editing.recipe=null; ['recipeName','recipeYieldQty','recipeYieldUnit','recipeNotes'].forEach(id=>setVal(id,'')); setVal('recipeActive','true'); }
function editRecipe(id){ const r=state.recipes.find(x=>x.id===id); if(!r)return; state.editing.recipe=id; setVal('recipeName',r.name); setVal('recipeCategory',r.category); setVal('recipeYieldQty',r.yield_quantity); setVal('recipeYieldUnit',r.yield_unit); setVal('recipeNotes',r.notes); setVal('recipeActive',String(r.active!==false)); }
async function deleteRecipe(id){ const r=state.recipes.find(x=>x.id===id); const ok=await confirmTypedDelete(`Delete recipe ${r?.name||''}? This cannot be undone.`, 'Delete recipe'); if(!ok) return; const done=await dbDelete('recipes',id); if(done){ showToast('Recipe deleted.'); await refreshAll(false); renderRecipes(); renderProductRecipes(); renderProducts(); }}
async function addRecipeItem(){ if(!val('recipeItemRecipe')||!val('recipeItemIngredient')) return showWarning('Select recipe and ingredient'); const saved=await dbInsert('recipe_items',{recipe_id:val('recipeItemRecipe'),ingredient_id:val('recipeItemIngredient'),quantity:num(val('recipeItemQty')),unit:val('recipeItemUnit'),waste_percent:num(val('recipeItemWaste'))}); if(!saved) return; showToast('Ingredient added to recipe.'); setVal('recipeItemQty',''); setVal('recipeItemWaste','0'); await refreshAll(false); renderRecipes(); renderRecipeItems(); renderProducts(); }
async function deleteRecipeItem(id){ const ok=await confirmTypedDelete('Delete this ingredient from the recipe?', 'Delete recipe ingredient'); if(!ok) return; const done=await dbDelete('recipe_items',id); if(done){ showToast('Recipe ingredient deleted.'); await refreshAll(false); renderRecipeItems(); renderRecipes(); renderProducts(); }}
function renderRecipeSelectors(){ ['recipeItemRecipe','builderRecipe'].forEach(id=>{ setSelectOptions(id, state.recipes, val(id), 'Select Recipe'); }); setSelectOptions('recipeItemIngredient', state.ingredients, val('recipeItemIngredient'), 'Select Ingredient'); }
function renderRecipeItems(){ const rid=val('recipeItemRecipe')||state.recipes[0]?.id; const items=state.recipeItems.filter(x=>x.recipe_id===rid); byId('recipeItemList').innerHTML=table(['Ingredient','Qty','Unit','Waste','Cost','Actions'],items.map(x=>{ const ing=state.ingredients.find(i=>i.id===x.ingredient_id)||{}; const cost=num(ing.effective_cost)*toBaseUnit(x.quantity,x.unit)*(1+num(x.waste_percent)/100); return `<tr><td>${escapeHtml(ing.name||'')}</td><td>${x.quantity}</td><td>${x.unit||''}</td><td>${pct(x.waste_percent)}</td><td>${money(cost)}</td><td><button class="btn-danger" onclick="deleteRecipeItem('${x.id}')">Delete</button></td></tr>`;})); }
function renderRecipes(){ renderRecipeSelectors(); renderRecipeItems(); const q=val('recipeSearch').toLowerCase(); const list=state.recipes.filter(r=>[r.name,r.category,r.yield_unit].join(' ').toLowerCase().includes(q)); byId('recipesTable').innerHTML=table(['Recipe','Category','Yield','Total Cost','Cost / Unit','Status','Actions'],list.map(r=>`<tr><td>${escapeHtml(r.name)}</td><td>${escapeHtml(r.category||'')}</td><td>${r.yield_quantity||0} ${escapeHtml(r.yield_unit||'')}</td><td><strong>${money(recipeTotalCost(r.id))}</strong></td><td>${money(recipeUnitCost(r))}/${unitFamily(r.yield_unit)}</td><td>${r.active===false?'Inactive':'Active'}</td><td><button onclick="editRecipe('${r.id}')">Edit</button><button class="btn-danger" onclick="deleteRecipe('${r.id}')">Delete</button></td></tr>`)); }
function exportRecipesCSV(){
 const rows=state.recipes.length ? state.recipes.map(r=>({'Recipe Name':r.name,'Category':r.category,'Yield Quantity':r.yield_quantity,'Yield Unit':r.yield_unit,'Notes':r.notes,'Active':r.active!==false,'Total Cost':recipeTotalCost(r.id),'Cost Per Unit':recipeUnitCost(r)})) : [{'Recipe Name':'Chicken Filling','Category':'Filling','Yield Quantity':1200,'Yield Unit':'g','Notes':'Sample recipe row','Active':true,'Total Cost':252,'Cost Per Unit':0.21}];
 downloadCSV(state.recipes.length?'khumbuka_recipes.csv':'khumbuka_recipes_sample_schema.csv', rows);
}
