function recipeUnitCost(recipe){ const cost=recipeTotalCost(recipe.id); const y=toBaseUnit(recipe.yield_quantity,recipe.yield_unit); return y?cost/y:0; }
function recipeTotalCost(recipeId){ return state.recipeItems.filter(x=>x.recipe_id===recipeId).reduce((sum,item)=>{ const ing=state.ingredients.find(i=>i.id===item.ingredient_id); if(!ing) return sum; const eff=num(ing.effective_cost ?? effectiveCost(ing.purchase_price,ing.wastage_percent)); const baseQty=toBaseUnit(item.quantity,item.unit); const wasteFactor=1+(num(item.waste_percent)/100); return sum + eff*baseQty*wasteFactor; },0); }
async function saveRecipe(){ const name=val('recipeName').trim(); if(!name) return alert('Recipe name required'); const row={name,category:val('recipeCategory'),yield_quantity:num(val('recipeYieldQty')),yield_unit:val('recipeYieldUnit'),notes:val('recipeNotes'),active:val('recipeActive')==='true',updated_at:new Date().toISOString()}; if(state.editing.recipe) await dbUpdate('recipes',state.editing.recipe,row); else await dbInsert('recipes',row); clearRecipeForm(); await refreshAll(false); renderRecipes(); renderRecipeSelectors(); }
function clearRecipeForm(){ state.editing.recipe=null; ['recipeName','recipeYieldQty','recipeYieldUnit','recipeNotes'].forEach(id=>setVal(id,'')); setVal('recipeActive','true'); }
function editRecipe(id){ const r=state.recipes.find(x=>x.id===id); if(!r)return; state.editing.recipe=id; setVal('recipeName',r.name); setVal('recipeCategory',r.category); setVal('recipeYieldQty',r.yield_quantity); setVal('recipeYieldUnit',r.yield_unit); setVal('recipeNotes',r.notes); setVal('recipeActive',String(r.active!==false)); }
async function deleteRecipe(id){ if(confirm('Delete recipe?')){ await dbDelete('recipes',id); await refreshAll(false); renderRecipes(); }}
async function addRecipeItem(){ if(!val('recipeItemRecipe')||!val('recipeItemIngredient')) return alert('Select recipe and ingredient'); await dbInsert('recipe_items',{recipe_id:val('recipeItemRecipe'),ingredient_id:val('recipeItemIngredient'),quantity:num(val('recipeItemQty')),unit:val('recipeItemUnit'),waste_percent:num(val('recipeItemWaste'))}); setVal('recipeItemQty',''); setVal('recipeItemWaste','0'); await refreshAll(false); renderRecipes(); renderRecipeItems(); }
async function deleteRecipeItem(id){ await dbDelete('recipe_items',id); await refreshAll(false); renderRecipeItems(); renderRecipes(); }
function renderRecipeSelectors(){ ['recipeItemRecipe','builderRecipe'].forEach(id=>{ if(byId(id)) byId(id).innerHTML=optionList(state.recipes); }); if(byId('recipeItemIngredient')) byId('recipeItemIngredient').innerHTML=optionList(state.ingredients); }
function renderRecipeItems(){ const rid=val('recipeItemRecipe')||state.recipes[0]?.id; const items=state.recipeItems.filter(x=>x.recipe_id===rid); byId('recipeItemList').innerHTML=table(['Ingredient','Qty','Unit','Waste','Cost','Actions'],items.map(x=>{ const ing=state.ingredients.find(i=>i.id===x.ingredient_id)||{}; const cost=num(ing.effective_cost)*toBaseUnit(x.quantity,x.unit)*(1+num(x.waste_percent)/100); return `<tr><td>${escapeHtml(ing.name||'')}</td><td>${x.quantity}</td><td>${x.unit||''}</td><td>${pct(x.waste_percent)}</td><td>${money(cost)}</td><td><button class="btn-danger" onclick="deleteRecipeItem('${x.id}')">Delete</button></td></tr>`;})); }
function renderRecipes(){ renderRecipeSelectors(); renderRecipeItems(); const q=val('recipeSearch').toLowerCase(); const list=state.recipes.filter(r=>(r.name||'').toLowerCase().includes(q)); byId('recipesTable').innerHTML=table(['Recipe','Category','Yield','Total Cost','Cost / Unit','Status','Actions'],list.map(r=>`<tr><td>${escapeHtml(r.name)}</td><td>${escapeHtml(r.category||'')}</td><td>${r.yield_quantity||0} ${escapeHtml(r.yield_unit||'')}</td><td><strong>${money(recipeTotalCost(r.id))}</strong></td><td>${money(recipeUnitCost(r))}/${unitFamily(r.yield_unit)}</td><td>${r.active===false?'Inactive':'Active'}</td><td><button onclick="editRecipe('${r.id}')">Edit</button><button class="btn-danger" onclick="deleteRecipe('${r.id}')">Delete</button></td></tr>`)); }
function exportRecipesCSV(){ downloadCSV('khumbuka_recipes.csv', state.recipes.map(r=>({...r,total_cost:recipeTotalCost(r.id),cost_per_unit:recipeUnitCost(r)}))); }
